# name: Norminette Check

# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - main
#       - master

# jobs:
#   run_norminette:
#     name: Run Norminette
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Install system dependencies
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y python3 python3-pip

#       - name: Install norminette
#         run: |
#           pip3 install --upgrade pip setuptools
#           pip3 install norminette

#       - name: Add pip local bin to PATH
#         run: echo "$HOME/.local/bin" >> $GITHUB_PATH

#       - name: Run norminette
#         run: norminette

# francinette + norm
name: Francinette + Norminette Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  run_francinette_and_norminette:
    name: Run Francinette & Norminette
    runs-on: ubuntu-latest

    env:
      TERM: xterm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential python3 python3-pip

      - name: Install Python dependencies
        run: |
          pip3 install --upgrade pip setuptools
          pip3 install gitpython halo toml norminette

      - name: Add pip local bin to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Clone francinette outside workspace
        run: |
          bash -c "$(curl -fsSL https://raw.github.com/xicodomingues/francinette/master/bin/install.sh)"

      - name: Add Francinette bin to PATH
        run: echo "$HOME/francinette" >> $GITHUB_PATH

      - name: Run norminette
        run: norminette

      - name: Run francinette tests
        working-directory: ${{ github.workspace }}
        env:
          TERM: dumb
          PYTHONUNBUFFERED: 1
        run: |
          sudo apt-get install -y util-linux
          script -q -c "$HOME/francinette/tester.sh" /dev/null
